### ISSUE TITLE
0.8 Android - Sub menus are not available in plates sorting menu

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#158]
![Screenshot_2023-12-08-21-31-18-06_e65191035490e46cdbaadce7822066c9.jpg](https://github.com/Xele02/UMO/assets/99509414/69fdc63f-17c3-4c39-87f3-9afc5425090f)

In plates selection screen, if you want to sort plates by L-skills and others, the sub-menus are not displayed.

**Comment by Xele02** [comment]
Dup of #119
