### ISSUE TITLE
[RhythmGame][Song] 0.10 Android - Stopping on the now loading

### ISSUE THREAD

**Issue by shadowdragon1123** [Xele02/UMO#168]
I use the Method 1.
Download the game data dump, extract and copy the data & mx directories to this folder. Android/data/com.UtaMacrossOffline.UtaMacrossOffline/files/
The game launch successfuly to the main page.
Tap start, it continute to the three quizs.
However, when I complete these quizs.
It stop on the page that sd character freya and kaname are in the middle, and now loading on the lower right corner.

**Comment by shadowdragon1123** [comment]
![`0WLY`%8OI3)J492{0P81K7](https://github.com/Xele02/UMO/assets/43469926/cb539ec8-22ed-4409-b99f-683f9efa441d)

**Comment by Xele02** [comment]
Hello,
Can you with at least the version 0.11, enable the debug and error log which is in the UMO option menu (Gamepad icon on bottom left in the title screen) and after reproducung the issue, send the log located in Android/data/com.UtaMacrossOffline.UtaMacrossOffline/files/Log.txt .

Thanks.

**Comment by Xele02** [comment]
No news, closing the bug
