### ISSUE TITLE
Macross Plus stuff bugged?

### ISSUE THREAD

**Issue by urielruthven** [Xele02/UMO#169]
When trying to launch INFORMATION HIGH from Macross Plus, the game freezes in the menu. It won't launch the music nor will other buttons work. This issue was noticed in Android. Could be my misuse of something or could be a bug in the game. Anyways, just wanted to leave this note in case it is seen.

**Comment by Xele02** [comment]
Hello, thanks for the report. This issue was also reported on the Discord and will be investigated for a next relase.

**Comment by Xele02** [comment]
Will be avaiable in next release
