### ISSUE TITLE
Android 0.11 - Costumes modified at team setting screen are not remembered

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#173]
Before launching a song, on team setting screen, if you modify costume of a diva, then close and restart the game, the costumes are not remembered by the game.

![IMG_20231225_121918.jpg](https://github.com/Xele02/UMO/assets/99509414/2c8b017c-bbd9-4b6d-8d39-22833b3dbe39)

**Comment by Tiger1970prod** [comment]
Exists on Unity Editor (PC) as well
