### ISSUE TITLE
Android 0.11 - No lighting effect on characters with song "ライオン(Lion)" (not Mirror version) of Macross F and 風は予告なく吹く of Macross Delta

### ISSUE THREAD

**Issue by PakuKashiwa** [Xele02/UMO#174]
**Setup Information**
Song Name/Id (see wiki) : "ライオン(Lion)" of Macross F and 風は予告なく吹く of Macross Delta
Num diva : All Divas
Diva infos : All Costumes

**Describe the bug**
No lighting on characters when playing with both Live and S-Live. 

**Screenshots**
n/a

**Log**
n/a

**Comment by PakuKashiwa** [comment]
Other songs with same issues:
- 愛。おぼえていますか (Do You Remember Love) of SDF Macross - Original ver. and Mirror ver. 
- 天使の絵の具 (Angel's paint) of SDF Macross - Original ver, no lighting on characters from some angles.
and more to be added. 
(I have had backup of almost all MVs with my youtube channel for comparison. If intrested, please visit http://www.youtube.com/@utamacross. Thanks.

**Comment by PakuKashiwa** [comment]
Pictures for comparison (please refer to lighting effect on characters)

1. Screen capture of Online ver. 
![Screenshot_2024-01-21-22-50-04-051_com google android youtube](https://github.com/Xele02/UMO/assets/156342922/946e360e-cb78-41cf-9caa-2e6a05733e18)

2. Screen capture of Offline ver.
![Screenshot_2024-01-21-22-45-25-330_com UtaMacrossOffline UtaMacrossOffline](https://github.com/Xele02/UMO/assets/156342922/56a4bf7d-66a7-416c-b75c-7f3b7a6fa447)

**Comment by PakuKashiwa** [comment]
Many songs are with the same issues except triggering 超歌姬mode for few seconds. Please fix. Thanks.

**Comment by Xele02** [comment]
Hello, thanks for your feedback. It will be looked at bug like that later when I'm done with version 1.0

**Comment by Xele02** [comment]
Lighting will be fixed in next version. Don't hesitate to open issue if you find other differences.
