### ISSUE TITLE
Android 0.11 & 0.11.1 freeze screen and no response(Samsung Galaxy S22 Ultra)

### ISSUE THREAD

**Issue by ruby2009g** [Xele02/UMO#176]
Android\data\com.UtaMacrossOffline.UtaMacrossOffline\files\Log.txt
only 

> 
> [[Warning] DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.UnityEngine.Object:Instantiate(T)
> XeApp.Game.GameManager:Create(GameObject)
> XeApp.Core.MainSceneBase:Awake()
> 
> 
> [Warning] DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.CriWare.CriWareInitializer:Initialize()
> UnityEngine.Object:Instantiate(T)
> XeApp.Game.GameManager:Create(GameObject)
> XeApp.Core.MainSceneBase:Awake()
> 
> 
> [Warning] DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.UnityEngine.Object:Instantiate(T)
> XeApp.Game.GameManager:Create(GameObject)
> XeApp.Core.MainSceneBase:Awake()
> 
> 
> [Log] load hadoopSaveFileJDDGPJDKHNE:IJBGPAENLJA()
> NKGJPJPHLIF:IJBGPAENLJA(MonoBehaviour)
> UnityEngine.Object:Instantiate(T)
> XeApp.Game.GameManager:Create(GameObject)
> XeApp.Core.MainSceneBase:Awake()
> 
> 
> [Log] load secureSaveFileJDDGPJDKHNE:IJBGPAENLJA()
> NKGJPJPHLIF:IJBGPAENLJA(MonoBehaviour)
> UnityEngine.Object:Instantiate(T)
> XeApp.Game.GameManager:Create(GameObject)
> XeApp.Core.MainSceneBase:Awake()
> 
> 
> [Log] ReSetupResolution(0,0)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] ReSetupResolution(0,0)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] SetupResolution:screenSizeType=0XeApp.Game.GameManager:AppSpecial()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] SetupResolution:AppEnvXeApp.Game.GameManager:AppSpecial()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] Screen.SetResolution(1423.911,664) startXeApp.Game.GameManager:SetupResolution(Single, Single)
> XeApp.Game.GameManager:AppSpecial()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] Screen.SetResolution(1423.911,664) endXeApp.Game.GameManager:SetupResolution(Single, Single)
> XeApp.Game.GameManager:AppSpecial()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.ScrollRect:LateUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.ScrollRect:LateUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.ScrollRect:LateUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.ScrollRect:LateUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
> 
> 
> [Log] ReSetupResolution(1423.911,664)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] SetupResolution:screenSizeType=0XeApp.Game.GameManager:ReInitScreen()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] SetupResolution:AppEnvXeApp.Game.GameManager:ReInitScreen()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] Screen.SetResolution(1428.2,666) startXeApp.Game.GameManager:SetupResolution(Single, Single)
> XeApp.Game.GameManager:ReInitScreen()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] Screen.SetResolution(1428.2,666) endXeApp.Game.GameManager:SetupResolution(Single, Single)
> XeApp.Game.GameManager:ReInitScreen()
> XeApp.Game.<Co_InitScreen>d__236:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
> 
> 
> [Log] ReSetupResolution(1428.2,666)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
> 
> 
> [Error] Material doesn't have a texture property '_MainTex'UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
> 
> 
> [Log] ReSetupResolution(1428.2,666)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] ReSetupResolution(1428.2,666)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] ReSetupResolution(1428.2,666)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] ReSetupResolution(1428.2,666)XeApp.Game.GameManager:RevertResolution()
> XeApp.Game.BootScene:DoUpdateEnter()
> XeApp.Core.MainSceneBase:UpdateEnter()
> 
> 
> [Log] buildOption=x7sH1ipz<EEOJBAHJAIN_Coroutine_Nil>d__97:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <MAMKIDBAINA_Coroutine_InitializeSystem>d__81:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] Finished Sakasho initialization.SakashoInitializer:Start()
> 
> 
> [Log] call PlayGamesPlatform.ActivateNDABOOOOENC:NCDLCIPGPNC_Login()
> XeApp.Game.<InitializeSystemCoroutine>d__247:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] GPGSセーブデータが存在しないNDABOOOOENC:KBCANNBANIL_ReadStatusOnSavedFile()
> NDABOOOOENC:NCDLCIPGPNC_Login()
> XeApp.Game.<InitializeSystemCoroutine>d__247:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel energy エナジー全回復NMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel info お知らせNMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel sns 超時空SNSNMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel vop VOPNMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel vvv22001ap AP全回復NMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel vvv22002deco デコルチャーモードNMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Create notif channel vvv32001limited_item 期限付きアイテムNMFABEKNBKJ:MABFNKCMEDL_CreateNotification(String, String, Int32)
> <LAGOJPPLDOH_Corotuine_BootInitilaize_FCM>d__27:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> MonoBehaviourExtensions:StartCoroutineWatched(MonoBehaviour, IEnumerator)
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Log] IsNotifyEnabledEOHDAOAJOHH:BBDNBCHOFIP()
> EOHDAOAJOHH:OJKIKODJJCD()
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Clear notif 1OJIHOFLJOMK:JCHLONCMPAJ_CancelNotif(Int32)
> EOHDAOAJOHH:OJKIKODJJCD()
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> 
> [Error] Clear notif 6OJIHOFLJOMK:JCHLONCMPAJ_CancelNotif(Int32)
> EOHDAOAJOHH:OJKIKODJJCD()
> <DFLFHJHBKOC_CoroutineAppBoot>d__26:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Xele02** [comment]
If you are on Android 11, next release will fix it. Closing the bug.
