### ISSUE TITLE
(PC, Unity) unable to rotate characters in preview screen 

### ISSUE THREAD

**Issue by Anomalous01** [Xele02/UMO#177]
Everything else works but when I try to view the character model, All I can do is use the scroll wheel to zoom in, nothing else works not sure if it's some option I left unchecked or if I installed it wrong

**Comment by Xele02** [comment]
Does this still happen ? I don't see any problem rotating the costume when in preview.

**Comment by Anomalous01** [comment]
never mind it was just me not realizing I had to hold the mouse button and move the mouse
