### ISSUE TITLE
[RhythmGame][Song] サヨナラノツバサ 〜 the end of triangle

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#23]
**Setup Information**
Song Name/Id (see wiki) : 32
Num diva : 6 & 7
Diva infos : 3 & 15 (for costume)

**Describe the bug**
Missing background during the song + rendering issue for special effect on stage

**Screenshots**
https://cdn.discordapp.com/attachments/557622156373000205/1002858457520685106/unknown.png
https://media.discordapp.net/attachments/557622156373000205/1002858705370492938/unknown.png

**Log**
[to be added]

**Comment by Xele02** [comment]
Looks fixed in current version
