### ISSUE TITLE
[Error] Using memoryadresses from more that 16GB of memoryUnityEngine.Resources:Load(String) BundleShaderInfo:Start()

### ISSUE THREAD

**Issue by Chn115** [Xele02/UMO#231]
[Error] Using memoryadresses from more that 16GB of memoryUnityEngine.Resources:Load(String)
BundleShaderInfo:Start()

**Comment by Xele02** [comment]
Hello. Sorry for the no answer as I didn't have any idea with just this error. But others people had this problem recently and I could get more debug info. The next version (1.0.18) should have this bug fixed and you should not have this problem anymore.
