### ISSUE TITLE
[RhythmGame][Song] ワルキューレはあきらめない

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#27]
**Setup Information**
Song : 138 ワルキューレはあきらめない
Num diva : 5
 0 : Diva : 7 - Costume : 1 - 0 Position : 1
 1 : Diva : 8 - Costume : 1 - 0 Position : 2
 2 : Diva : 2 - Costume : 1 - 0 Position : 3
 3 : Diva : 10 - Costume : 1 - 0 Position : 4
 4 : Diva : 6 - Costume : 1 - 0 Position : 5

**Describe the bug**
Minor rendering issues of light special effect.
+ UMO/Copy song setup for bug report is reporting wrong song ID (id 137 for this song instead of id 138).

**Screenshots**
UMO: ![UMO](https://user-images.githubusercontent.com/99509414/182250430-99c19c02-2acf-47f3-ab94-42c9850bb5a2.PNG)
Reference: ![Réference](https://user-images.githubusercontent.com/99509414/182251407-3aa83838-2775-4a53-a515-c4a6809a055a.PNG)

**Comment by Xele02** [comment]
commit 559f614d57d303aea403367ba224561d093d1b68 fix song name.
