### ISSUE TITLE
Black screen after start menu

### ISSUE THREAD

**Issue by Nylus299** [Xele02/UMO#273]
Games work on my old phone but not on my new one.
Followed all the step to install properly.
after touching the screen to enter the game, a black screen appear and stay that way, games is not frozen as i can still hear the music and see the touch screen effect.
Phone is Asus Rog 7 ultimate. (kinda big screen)

Here is a log if that can help:
[Log.txt](https://github.com/user-attachments/files/17010273/Log.txt)

And a small video from my perspective:
https://github.com/user-attachments/assets/76cddbf4-55e4-4a8b-81fc-f3b8804b40ca

**Comment by Xele02** [comment]
Did you enable the debug log & error log in UMO options (gamepad on start screen) ? The log should be more filled and I should get more infos.

**Comment by Nylus299** [comment]
You're right !
Here is the log with enable info log and enable debug log:

![Log.txt](https://github.com/user-attachments/files/17019760/Log.txt)

**Comment by Xele02** [comment]
Thanks, the log confirm what I thought the bug is, even if I have no idea why it's happening. I'll try to add some new config option to test in the next build to see if some can be used for the phon that have this problem.
I'll write a answer when it's ready

**Comment by Xele02** [comment]
So the next version, which should be this weekend, will have 2 options :
![image](https://github.com/user-attachments/assets/b19cb3b9-3725-484d-8f3f-af5b853a331b)

Try the first one first. It could be working, and will be the one which will slow down the game the less. If it don't work, try the second one. This one should work, but can add some hiccup to the game unfortunately.

When you enable one option, be sure to validate the popup and completely restart the game to test. Hope this will be a solution.

**Comment by Xele02** [comment]
Version 1.0.10 is available with those option. Hope one will works.

**Comment by Nylus299** [comment]
Redownloaded the entire game and the new version (v1.0.10) just to be sure.
Tried each option and still doesn't work. There wasn't any popup to restart the game but i restarted the game manually each time.
The issue is still the same as the first video.

here is the log with normal priority + enable info/error log:
[Log.txt](https://github.com/user-attachments/files/17090801/Log.txt)

here is the log with coroutine + enable info/error log:
[Log.txt](https://github.com/user-attachments/files/17090807/Log.txt)

**Comment by Xele02** [comment]
Thanks, got similar report from other player. Indeed the normal thread didn't change anything. I don't know if it's not working or just the print don't work on thread with this android.

But the coroutine one show a Write access error, which is interesting. Android 11 changed stuff and it's probably that which broke. I'll try some stuff again for next version. Weird things is that the UMO popup save also a file (like the thread/coroutine setup) and this one is working...

**Comment by Xele02** [comment]
I made a new version to test. You can try with https://umo.xele.org/UtaMacross_v1_0_10_test.apk . Give me log if it's still not working.

**Comment by Nylus299** [comment]
It work ! You're amazing, Thank you so much ! I'm so happy lol.

**Comment by Xele02** [comment]
Yep, got the same feedback on the Discord. Closing the bug then.
