### ISSUE TITLE
1.0.16 The game crashes a lot

### ISSUE THREAD

**Issue by Glitch524** [Xele02/UMO#323]
I update to 1.0.16 these days, but it crashes everytime.

Then I reinstall the game and open, it crash before the title sonetime.
When I use Umosever try to download the files when I can get in, it crashed when the sever send the getfile.json

After I copy all the files through usb cable, it works?
At least I can continue to start a new game, but it will sometimes crash at:

1. 'now loading'
2. Intro when I clicked 'skip'
3. node tuning after the intro

Even if I can pass all of that things, it will end up crashing at the song's title after the tuning everytime

I tried to get in using cheat save, but the game still crashed, the furthest I can reach is the now loading screen with tips

I don't know what happened, but I can play this game well at 1.0.0 months ago
My phone is sony 1 iv, android version is 14

**Comment by Xele02** [comment]
Hi,
Usually the game crash because of broken files. Did you try enabling game data check in UMO Settings then continue to start the game, it will recheck all files.
Else you can enabe the logs and post your log file after the game crashed so I can check if I see something usefull.

**Comment by Glitch524** [comment]
[Log.txt](https://github.com/user-attachments/files/18141504/Log.txt)
Yes I tried the data check several times, but it didn't found some file need to fix.
About the error log, Is this file the log file you need? Hope this helps

**Comment by Xele02** [comment]
Yep that's the one. Did you also enable the "info log" ? Looks like I'm missing those level of log in the file to have more useless data but could help. 
I guess the game crashed at the end for this log, around the note timing adjustment ?
I don't see any error detected by the engine before the crash, that's why perhaps there will be something with the info log level too.

**Comment by Glitch524** [comment]
[Log.txt](https://github.com/user-attachments/files/18141598/Log.txt)
This time I enabled both log to start the game
The "log.txt" crashed at the song title after the adjustment
[Log (1).txt](https://github.com/user-attachments/files/18141652/Log.1.txt)
And the"log (1).txt" crashed at the black screen right before the adjustment

**Comment by Xele02** [comment]
Ok, not much more information of what could happen. Another thing to try is if you have this option on your phone after a crash : https://support.garmin.com/en-US/?faq=2tSRRp0RGn4BH6ZnstQbL7 . Then send it to me. Not sure if you'll be able to post here depending on the size. Else you can upload on a google drive and share a link I guess. Or send it on my mail :  git at xele.org .

**Comment by Glitch524** [comment]
Is that mean I should create the bugreport file after the game crashes? 
[bugreport-XQ-CT72_CN-64.2.F.2.184-2024-12-16-03-16-50.zip](https://github.com/user-attachments/files/18141748/bugreport-XQ-CT72_CN-64.2.F.2.184-2024-12-16-03-16-50.zip)
This file is what I get

**Comment by Xele02** [comment]
Yep, I downloaded the file. You can remove it from your message, I don't know exactly whatit contains so I think it's better to not let it public.

**Comment by Xele02** [comment]
I found an usefull information which looks like a asset corruption. When you tried to recheck the asset, did you start the game with the cheat account. The check is done after the tutorial so it won't work with a new account I think. There should be a popup window saying it's rechecking the 40000+ files. It takes around 5 min to do.

**Comment by Glitch524** [comment]
![Screenshot_20241216094448094](https://github.com/user-attachments/assets/9d4713c7-10cf-4228-b583-0aa455d1c932)
I try to start with a cheat account, it crashed at this loading screen

Is the "recheck the asset" means integrity check? I try that with cheat account too, still no file need to fix

**Comment by Xele02** [comment]
Ok. Someone else on discord was reporting also bug in android 14 after a system update. I found out unity fixed some weird memory management in a version on unity 2018 a little newer. I'll make a build in a few days with the editor updated so you can test if by chance it fixes your problems.

**Comment by Glitch524** [comment]
OK, thanks for your patience and your hard work :)

**Comment by Xele02** [comment]
I made a new build, you can try this version and pray it's better. https://github.com/Xele02/UMO/releases/download/v1.0.17/UtaMacross_v1_0_17_test.apk

**Comment by Glitch524** [comment]
Ok, I'll try it

**Comment by Glitch524** [comment]
Yes! I can get in and play the game with no crashes now! Thank you.
