### ISSUE TITLE
[Menu] Song select going weird when playing with 4/6 lanes buttons, event buttons and sorting buttons too much

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#65]
On song select menu, if you play a bit too much with the 4/6 lanes button, the events button and the series sorting button (upper left), you can sometimes reach the bug.

The bug lead to:
- Have 6 lanes identified as 4 lanes on the menu,
- Force you back into the events song selection menu when you change songs.

Refers to the log for more information. The bug can be repeat by doing a weird combination of the three mentioned buttons.

[Editor.log](https://github.com/Xele02/UMO/files/9437919/Editor.log)
![image](https://user-images.githubusercontent.com/99509414/187029440-df779c8a-8cc4-4d93-928e-3022e1af837d.png)

**Comment by Xele02** [comment]
Looks ok in current WIP branch, avaiable in next release
