### ISSUE TITLE
[Song] What 'bout my star?@.Formo 

### ISSUE THREAD

**Issue by Ganonzord** [Xele02/UMO#66]
**Song:**
What 'bout my star?@.Formo   ID 72

Num diva : 
6 

Diva infos : 
Ranka / All 

- The song cuts out before the pose animation ends.

https://www.youtube.com/watch?v=z9vkrHBn3dQ

**Log**

[Editor.log](https://github.com/Xele02/UMO/files/9483484/Editor.log)

**Comment by Xele02** [comment]
Fixed in WIP branch, avaiable in next release
