### ISSUE TITLE
[RhythmGame][Song] ダイナム超合金 - Left click stop the animation but you can't restart it

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#74]
**Setup Information**
Song : 143 ダイナム超合金
Num diva : 1
 0 : Diva : 6 - Costume : 40 - 0 Position : 1
Valkyrie : 65
Difficulty : Hard, Line6 : False

**Describe the bug**
If you left click on the scene, it stops the scene (as it was in the original game). Yet, you have no pop up to restart the scene or leave the scene.

**Screenshots**
https://discord.com/channels/342651627444109312/557622156373000205/1046447354695385201

**Log**
No need.

**Comment by Xele02** [comment]
Fixed in WIP branch, avaiable in next release
