### ISSUE TITLE
v0.4 - Gameplay issue - Soft lock note button

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#76]
During play, for some reasons, one of the four notes buttons can be soft lock. By pushing it again, you can't unstuck it.
You can't use it any longer during the song, even if you push it again (miss everytime).

The second note button is soft lock on the picture as an example.
![image](https://user-images.githubusercontent.com/99509414/215216899-550eb91a-9c77-43d9-8bd4-23bf90408925.png)

**Comment by Kilarn** [comment]
It seems to happen especially when you miss a lot of notes on the line.
Tried absolute 5 in normal difficulty without playing : all keys are soft lock.
Tried absolute 5 in normal difficulty playing normally : no soft lock.

**Comment by Xele02** [comment]
Working better in WIP branch, still have some rare case when one input is not responding

**Comment by Xele02** [comment]
I didn't have touch locked lately, but some times note not beeing valided even when pressed at the right time. If that happens, use the menu entry UMO > Create song notes data to generate a debug file. The path of the created file will be printed in the log, then send it here.

**Comment by Xele02** [comment]
Closing this one as didn't see any note stuck lately. Issue #127 opened for current notes problem.
