### ISSUE TITLE
v0.4a2 - Impossibility to add plates on second character

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#77]
![image](https://user-images.githubusercontent.com/99509414/216710809-62b279e0-dbab-482e-9c99-d78ca6ca037f.png)
When you select the second singer and try to add plates, the game doesn't respond to the click and doesn't add the plate to the second singer.

**Comment by Xele02** [comment]
Looks working now in WIP branch. Avaiable in next release
