### ISSUE TITLE
v0.4a2 - Long notes are interrupted for no reason

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#80]
During plays, long notes are sometimes interrupted before release of the keys. It seems to happen not at the start of the song but after the middle part. Once it start to happen in the song, it occurs each long note until the end of the play.

**Comment by Kilarn** [comment]
See example at https://youtu.be/60WXyOpbKOM?t=1908 31:53
Seems to be especially present on double long notes.

**Comment by Xele02** [comment]
Fixed on current WIP branch, avaiable on next release
