### ISSUE TITLE
v0.4a2 - UI minor issue - Shown difficulty not consistent with chosen difficulty

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#81]
On team selection screen, the difficulty shown in the bottom part of the UI is not consistent with the difficulty chosen on the song selection screen. It only displays "easy" whatever the difficulty.
![image](https://user-images.githubusercontent.com/99509414/219941160-d0a922c1-caa3-4cc1-8d4d-43cd5d43cbe5.png)

**Comment by Xele02** [comment]
UI working in WIP branch, avaiable in next release
