### ISSUE TITLE
v0.4.2 PC/Android - Note speed

### ISSUE THREAD

**Issue by eukatoss** [Xele02/UMO#91]
Occurs with every song and diva

If the note speed is set to X.1~X.9, speed will force set in to 1.0 ingame

![image](https://github.com/Xele02/UMO/assets/70463147/8a9fb24d-c025-472c-b840-1f854c5394f1)

Ingame with 9.2 spd

![image](https://github.com/Xele02/UMO/assets/70463147/3484b1f2-dc14-4f8c-a762-10c5e02f4c27)

Ingame with 9.0 spd

**Comment by Xele02** [comment]
Fixed for 0.4.3
