### ISSUE TITLE
v0.4.2 PC/Android - Bug with スタンダード編成

### ISSUE THREAD

**Issue by eukatoss** [Xele02/UMO#92]
'Standard setup'(スタンダード編成) button does not work on s-live mode, as if it's not implemented

![image](https://github.com/Xele02/UMO/assets/70463147/444a37d0-7f8f-4200-9c05-efff9346df68)

![image](https://github.com/Xele02/UMO/assets/70463147/2edb32ab-a75b-4a0f-9541-7d7b489300bd)

But works fine with regular live, using superdimensional prism 

![image](https://github.com/Xele02/UMO/assets/70463147/219d95c0-cf71-4892-8cd2-ad531cce4a0c)

**Comment by Xele02** [comment]
Fixed for 0.4.3
