### ISSUE TITLE
v4.2.0 PC/Android - Game freeze

### ISSUE THREAD

**Issue by eukatoss** [Xele02/UMO#95]
Always reproduces

Diva tab -> Diva list button -> clink on any diva

![image](https://github.com/Xele02/UMO/assets/70463147/9d91f423-d2aa-4439-a766-9a81896d3a5c)

There are 2 costume change buttons. Either the screen turns grey immediately(2nd button), or it takes you to diva costume change screen but if you tab 'go back' button in there the screen turns grey(3rd button). Cannot click anything after that.

![image](https://github.com/Xele02/UMO/assets/70463147/de9dfe88-df02-4cc7-a42d-ebd401a70fd0)

**Comment by Xele02** [comment]
Freeze fixed for 0.4.3, transfering display of buttons to new bug report #97
