### ISSUE TITLE
v0.4.2 Home diva T pose

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#98]
Going into diva menu, exploring it and going back on the home menu lead to T pose for the hope diva

![Screenshot_2023-08-24-16-53-31-95_e65191035490e46cdbaadce7822066c9](https://github.com/Xele02/UMO/assets/99509414/d65eb2fc-2f29-4006-9d9a-ef8ce56ec264)

**Comment by Xele02** [comment]
Duplicate of #96
